org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


## Mod Properties
modId=ae2randomsorting
modName=AE2 Random Sorting
modLicense=BSD 2-Clause License
modVersion=1.1.0
modGroupId=io.github.makaseloli.ae2randomsorting
modAuthors=makaseloli
modDescription=Adds random sorting to Applied Energistics 2 terminals.
modDisplayUrl=https://github.com/makaseloli/AE2-Random-Sorting
modIssueTrackerUrl=https://github.com/makaseloli/AE2-Random-Sorting/issues
modCredits=


## Fabric Mod Properties
modFabricEntrypoint=io.github.makaseloli.ae2randomsorting.ModMain
modFabricClientEntrypoint=io.github.makaseloli.ae2randomsorting.client.ModClient
